version: '2'
services:
    web:
    	container_name: retinopatia-api 
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
