version: '3.8'
services: 
    api-service:
        build: ./
        volumes: 
            - ./usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            DOCKER_HOST: http://172.17.0.1:5000/
